puts "seeding the reports"

report_list = [
	["The Sharing Economy", "Released in May of 2014", "http://www.prosumer-report.com/blog/category/the-new-consumer-and-the-sharing-economy/"],
	["Brand Relevance", "Released in December of 2013", "http://www.prosumer-report.com/blog/category/brand-relevance/"],
	["Youth", "Released in September of 2014", "http://www.prosumer-report.com/blog/category/youth/"]
]
Report.delete_all
report_list.each do |title, description, link|
	Report.create(title: title, description: description, link: link)
end

puts "seeding the questions"

question_list = [
	["Companies/retailers should help customers resell their goods.", "Ethics", "The Sharing Economy"],
	["Brands are an important part of the creative content online.", "Online", "The Sharing Economy"],
	["I like it when brands ask consumers to get involved through crowdsourcing, creating brand videos, etc.", "Engagement", "Brand Relevance"],
	["It makes me feel good when I see someone I admire using the same brand I use.", "Engagement", "Brand Relevance"],
	["I have no interest in brands.", "Engagement", "Youth"],
	["Brands play an essential role in my life.", "Engagement", "Youth"],
	["I have the power to help a brand succeed or fail.", "Engagement", "Youth"],
	["I encourage my friends to use the brands I really like.", "Engagement", "Youth"],
	["I would rather pay more for a well-known brand than take a chance on a brand that isn't as established.", "Engagement", "Youth"],
	["Following a brand on a social networking site (e.g., Facebook, Twitter) is a waste of time.", "Engagement", "Youth"],
	["I only follow brands on social media to get discounts/special deals.", "Engagement", "Youth"],
	["In general, brands don't take young people seriously enough.", "Engagement", "Youth"],
	["Most brands pay too little attention to older consumers.", "Engagement", "Youth"],
	["As long as a brand is useful, I don't care if it shares my values.", "Engagement", "Youth"],
	["When I find a brand that fits my personality, I tend to be loyal to it.", "Engagement", "Youth"]


]

Question.delete_all
question_list.each do |title, tag, report_title|
	@report_title = Report.find_by title: report_title

	Question.create(title: title, tag: tag, report_id: @report_title.id)
end

puts "seeding the responses"

response_list = [
	["total", "Strongly Agree", 5, 2713, DateTime.new(2013,6,30), "Companies/retailers should help customers resell their goods."],
	["US", "Strongly Agree", 5, 96, DateTime.new(2013,6,30), "Companies/retailers should help customers resell their goods."],
	["UK", "Strongly Agree", 5, 69, DateTime.new(2013,6,30), "Companies/retailers should help customers resell their goods."],
	["total", "Somewhat Agree", 5, 3828, DateTime.new(2013,6,30), "Companies/retailers should help customers resell their goods."],
	["US", "Somewhat Agree", 5, 142, DateTime.new(2013,6,30), "Companies/retailers should help customers resell their goods."],
	["UK", "Somewhat Agree", 5, 198, DateTime.new(2013,6,30), "Companies/retailers should help customers resell their goods."],	
	["total", "Neither agree nor disagree", 5, 3017, DateTime.new(2013,6,30), "Companies/retailers should help customers resell their goods."],
	["US", "Neither agree nor disagree", 5, 170, DateTime.new(2013,6,30), "Companies/retailers should help customers resell their goods."],
	["UK", "Neither agree nor disagree", 5, 173, DateTime.new(2013,6,30), "Companies/retailers should help customers resell their goods."],	
	["total", "Somewhat disagree", 5, 740, DateTime.new(2013,6,30), "Companies/retailers should help customers resell their goods."],
	["US", "Somewhat disagree", 5, 56, DateTime.new(2013,6,30), "Companies/retailers should help customers resell their goods."],
	["UK", "Somewhat disagree", 5, 53, DateTime.new(2013,6,30), "Companies/retailers should help customers resell their goods."],		
	["total", "Strongly disagree", 5, 276, DateTime.new(2013,6,30), "Companies/retailers should help customers resell their goods."],
	["US", "Strongly disagree", 5, 37, DateTime.new(2013,6,30), "Companies/retailers should help customers resell their goods."],
	["UK", "Strongly disagree", 5, 9, DateTime.new(2013,6,30), "Companies/retailers should help customers resell their goods."],
	# Question 2
	["total", "Strongly Agree", 5, 1820, DateTime.new(2013,6,30), "Brands are an important part of the creative content online."],
	["US", "Strongly Agree", 5, 72, DateTime.new(2013,6,30), "Brands are an important part of the creative content online."],
	["UK", "Strongly Agree", 5, 44, DateTime.new(2013,6,30), "Brands are an important part of the creative content online."],
	["total", "Somewhat Agree", 5, 3815, DateTime.new(2013,6,30), "Brands are an important part of the creative content online."],
	["US", "Somewhat Agree", 5, 173, DateTime.new(2013,6,30), "Brands are an important part of the creative content online."],
	["UK", "Somewhat Agree", 5, 140, DateTime.new(2013,6,30), "Brands are an important part of the creative content online."],	
	["total", "Neither agree nor disagree", 5, 3797, DateTime.new(2013,6,30), "Brands are an important part of the creative content online."],
	["US", "Neither agree nor disagree", 5, 193, DateTime.new(2013,6,30), "Brands are an important part of the creative content online."],
	["UK", "Neither agree nor disagree", 5, 247, DateTime.new(2013,6,30), "Brands are an important part of the creative content online."],	
	["total", "Somewhat disagree", 5, 824, DateTime.new(2013,6,30), "Brands are an important part of the creative content online."],
	["US", "Somewhat disagree", 5, 50, DateTime.new(2013,6,30), "Brands are an important part of the creative content online."],
	["UK", "Somewhat disagree", 5, 44, DateTime.new(2013,6,30), "Brands are an important part of the creative content online."],		
	["total", "Strongly disagree", 5, 318, DateTime.new(2013,6,30), "Brands are an important part of the creative content online."],
	["US", "Strongly disagree", 5, 12, DateTime.new(2013,6,30), "Brands are an important part of the creative content online."],
	["UK", "Strongly disagree", 5, 26, DateTime.new(2013,6,30), "Brands are an important part of the creative content online."],		
	# Question 3
	["total", "Strongly Agree", 5, 1622, DateTime.new(2013,6,30), "I like it when brands ask consumers to get involved through crowdsourcing, creating brand videos, etc."],
	["US", "Strongly Agree", 5, 64, DateTime.new(2013,6,30), "I like it when brands ask consumers to get involved through crowdsourcing, creating brand videos, etc."],
	["UK", "Strongly Agree", 5, 42, DateTime.new(2013,6,30), "I like it when brands ask consumers to get involved through crowdsourcing, creating brand videos, etc."],
	["total", "Somewhat Agree", 5, 3170, DateTime.new(2013,6,30), "I like it when brands ask consumers to get involved through crowdsourcing, creating brand videos, etc."],
	["US", "Somewhat Agree", 5, 127, DateTime.new(2013,6,30), "I like it when brands ask consumers to get involved through crowdsourcing, creating brand videos, etc."],
	["UK", "Somewhat Agree", 5, 121, DateTime.new(2013,6,30), "I like it when brands ask consumers to get involved through crowdsourcing, creating brand videos, etc."],	
	["total", "Neither agree nor disagree", 5, 4384, DateTime.new(2013,6,30), "I like it when brands ask consumers to get involved through crowdsourcing, creating brand videos, etc."],
	["US", "Neither agree nor disagree", 5, 231, DateTime.new(2013,6,30), "I like it when brands ask consumers to get involved through crowdsourcing, creating brand videos, etc."],
	["UK", "Neither agree nor disagree", 5, 265, DateTime.new(2013,6,30), "I like it when brands ask consumers to get involved through crowdsourcing, creating brand videos, etc."],	
	["total", "Somewhat disagree", 5, 958, DateTime.new(2013,6,30), "I like it when brands ask consumers to get involved through crowdsourcing, creating brand videos, etc."],
	["US", "Somewhat disagree", 5, 50, DateTime.new(2013,6,30), "I like it when brands ask consumers to get involved through crowdsourcing, creating brand videos, etc."],
	["UK", "Somewhat disagree", 5, 56, DateTime.new(2013,6,30), "I like it when brands ask consumers to get involved through crowdsourcing, creating brand videos, etc."],		
	["total", "Strongly disagree", 5, 440, DateTime.new(2013,6,30), "I like it when brands ask consumers to get involved through crowdsourcing, creating brand videos, etc."],
	["US", "Strongly disagree", 5, 29, DateTime.new(2013,6,30), "I like it when brands ask consumers to get involved through crowdsourcing, creating brand videos, etc."],
	["UK", "Strongly disagree", 5, 18, DateTime.new(2013,6,30), "I like it when brands ask consumers to get involved through crowdsourcing, creating brand videos, etc."],	
	# Question 4		
	["total", "Strongly Agree", 5, 2167, DateTime.new(2013,6,30), "It makes me feel good when I see someone I admire using the same brand I use."],
	["US", "Strongly Agree", 5, 79, DateTime.new(2013,6,30), "It makes me feel good when I see someone I admire using the same brand I use."],
	["UK", "Strongly Agree", 5, 56, DateTime.new(2013,6,30), "It makes me feel good when I see someone I admire using the same brand I use."],
	["total", "Somewhat Agree", 4, 3367, DateTime.new(2013,6,30), "It makes me feel good when I see someone I admire using the same brand I use."],
	["US", "Somewhat Agree", 4, 170, DateTime.new(2013,6,30), "It makes me feel good when I see someone I admire using the same brand I use."],
	["UK", "Somewhat Agree", 4, 126, DateTime.new(2013,6,30), "It makes me feel good when I see someone I admire using the same brand I use."],	
	["total", "Neither agree nor disagree", 3, 3455, DateTime.new(2013,6,30), "It makes me feel good when I see someone I admire using the same brand I use."],
	["US", "Neither agree nor disagree", 3, 195, DateTime.new(2013,6,30), "It makes me feel good when I see someone I admire using the same brand I use."],
	["UK", "Neither agree nor disagree", 3, 215, DateTime.new(2013,6,30), "It makes me feel good when I see someone I admire using the same brand I use."],	
	["total", "Somewhat disagree", 2, 958, DateTime.new(2013,6,30), "It makes me feel good when I see someone I admire using the same brand I use."],
	["US", "Somewhat disagree", 2, 40, DateTime.new(2013,6,30), "It makes me feel good when I see someone I admire using the same brand I use."],
	["UK", "Somewhat disagree", 2, 60, DateTime.new(2013,6,30), "It makes me feel good when I see someone I admire using the same brand I use."],		
	["total", "Strongly disagree", 1, 626, DateTime.new(2013,6,30), "It makes me feel good when I see someone I admire using the same brand I use."],
	["US", "Strongly disagree", 1, 17, DateTime.new(2013,6,30), "It makes me feel good when I see someone I admire using the same brand I use."],
	["UK", "Strongly disagree", 1, 45, DateTime.new(2013,6,30), "It makes me feel good when I see someone I admire using the same brand I use."],
	# Question 5
	["total", "Strongly Agree", 5, 1126, DateTime.new(2013,6,30), "I have no interest in brands."],
	["US", "Strongly Agree", 5, 45, DateTime.new(2013,6,30), "I have no interest in brands."],
	["UK", "Strongly Agree", 5, 46, DateTime.new(2013,6,30), "I have no interest in brands."],
	["total", "Somewhat Agree", 4, 2134, DateTime.new(2013,6,30), "I have no interest in brands."],
	["US", "Somewhat Agree", 4, 73, DateTime.new(2013,6,30), "I have no interest in brands."],
	["UK", "Somewhat Agree", 4, 101, DateTime.new(2013,6,30), "I have no interest in brands."],	
	["total", "Neither agree nor disagree", 3, 3436, DateTime.new(2013,6,30), "I have no interest in brands."],
	["US", "Neither agree nor disagree", 3, 192, DateTime.new(2013,6,30), "I have no interest in brands."],
	["UK", "Neither agree nor disagree", 3, 205, DateTime.new(2013,6,30), "I have no interest in brands."],	
	["total", "Somewhat disagree", 2, 2520, DateTime.new(2013,6,30), "I have no interest in brands."],
	["US", "Somewhat disagree", 2, 129, DateTime.new(2013,6,30), "I have no interest in brands."],
	["UK", "Somewhat disagree", 2, 116, DateTime.new(2013,6,30), "I have no interest in brands."],		
	["total", "Strongly disagree", 1, 1359, DateTime.new(2013,6,30), "I have no interest in brands."],
	["US", "Strongly disagree", 1, 62, DateTime.new(2013,6,30), "I have no interest in brands."],
	["UK", "Strongly disagree", 1, 34, DateTime.new(2013,6,30), "I have no interest in brands."],
	# Question 6
	["total", "Strongly Agree", 5, 1281, DateTime.new(2013,6,30), "Brands play an essential role in my life."],
	["US", "Strongly Agree", 5, 55, DateTime.new(2013,6,30), "Brands play an essential role in my life."],
	["UK", "Strongly Agree", 5, 39, DateTime.new(2013,6,30), "Brands play an essential role in my life."],
	["total", "Somewhat Agree", 4, 2670, DateTime.new(2013,6,30), "Brands play an essential role in my life."],
	["US", "Somewhat Agree", 4, 123, DateTime.new(2013,6,30), "Brands play an essential role in my life."],
	["UK", "Somewhat Agree", 4, 105, DateTime.new(2013,6,30), "Brands play an essential role in my life."],	
	["total", "Neither agree nor disagree", 3, 3662, DateTime.new(2013,6,30), "Brands play an essential role in my life."],
	["US", "Neither agree nor disagree", 3, 193, DateTime.new(2013,6,30), "Brands play an essential role in my life."],
	["UK", "Neither agree nor disagree", 3, 197, DateTime.new(2013,6,30), "Brands play an essential role in my life."],	
	["total", "Somewhat disagree", 2, 1874, DateTime.new(2013,6,30), "Brands play an essential role in my life."],
	["US", "Somewhat disagree", 2, 102, DateTime.new(2013,6,30), "Brands play an essential role in my life."],
	["UK", "Somewhat disagree", 2, 94, DateTime.new(2013,6,30), "Brands play an essential role in my life."],		
	["total", "Strongly disagree", 1, 1087, DateTime.new(2013,6,30), "Brands play an essential role in my life."],
	["US", "Strongly disagree", 1, 29, DateTime.new(2013,6,30), "Brands play an essential role in my life."],
	["UK", "Strongly disagree", 1, 67, DateTime.new(2013,6,30), "Brands play an essential role in my life."],						
	# Question 7
	["total", "Strongly Agree", 5, 1337, DateTime.new(2013,6,30), "I have the power to help a brand succeed or fail."],
	["US", "Strongly Agree", 5, 78, DateTime.new(2013,6,30), "I have the power to help a brand succeed or fail."],
	["UK", "Strongly Agree", 5, 36, DateTime.new(2013,6,30), "I have the power to help a brand succeed or fail."],
	["total", "Somewhat Agree", 4, 2847, DateTime.new(2013,6,30), "I have the power to help a brand succeed or fail."],
	["US", "Somewhat Agree", 4, 167, DateTime.new(2013,6,30), "I have the power to help a brand succeed or fail."],
	["UK", "Somewhat Agree", 4, 133, DateTime.new(2013,6,30), "I have the power to help a brand succeed or fail."],	
	["total", "Neither agree nor disagree", 3, 3767, DateTime.new(2013,6,30), "I have the power to help a brand succeed or fail."],
	["US", "Neither agree nor disagree", 3, 186, DateTime.new(2013,6,30), "I have the power to help a brand succeed or fail."],
	["UK", "Neither agree nor disagree", 3, 232, DateTime.new(2013,6,30), "I have the power to help a brand succeed or fail."],	
	["total", "Somewhat disagree", 2, 1564, DateTime.new(2013,6,30), "I have the power to help a brand succeed or fail."],
	["US", "Somewhat disagree", 2, 51, DateTime.new(2013,6,30), "I have the power to help a brand succeed or fail."],
	["UK", "Somewhat disagree", 2, 67, DateTime.new(2013,6,30), "I have the power to help a brand succeed or fail."],		
	["total", "Strongly disagree", 1, 1058, DateTime.new(2013,6,30), "I have the power to help a brand succeed or fail."],
	["US", "Strongly disagree", 1, 19, DateTime.new(2013,6,30), "I have the power to help a brand succeed or fail."],
	["UK", "Strongly disagree", 1, 33, DateTime.new(2013,6,30), "I have the power to help a brand succeed or fail."],							
	# Question 8
	["total", "Strongly Agree", 5, 2123, DateTime.new(2013,6,30), "I encourage my friends to use the brands I really like."],
	["US", "Strongly Agree", 5, 77, DateTime.new(2013,6,30), "I encourage my friends to use the brands I really like."],
	["UK", "Strongly Agree", 5, 51, DateTime.new(2013,6,30), "I encourage my friends to use the brands I really like."],
	["total", "Somewhat Agree", 4, 3720, DateTime.new(2013,6,30), "I encourage my friends to use the brands I really like."],
	["US", "Somewhat Agree", 4, 168, DateTime.new(2013,6,30), "I encourage my friends to use the brands I really like."],
	["UK", "Somewhat Agree", 4, 154, DateTime.new(2013,6,30), "I encourage my friends to use the brands I really like."],	
	["total", "Neither agree nor disagree", 3, 3122, DateTime.new(2013,6,30), "I encourage my friends to use the brands I really like."],
	["US", "Neither agree nor disagree", 3, 172, DateTime.new(2013,6,30), "I encourage my friends to use the brands I really like."],
	["UK", "Neither agree nor disagree", 3, 216, DateTime.new(2013,6,30), "I encourage my friends to use the brands I really like."],	
	["total", "Somewhat disagree", 2, 999, DateTime.new(2013,6,30), "I encourage my friends to use the brands I really like."],
	["US", "Somewhat disagree", 2, 57, DateTime.new(2013,6,30), "I encourage my friends to use the brands I really like."],
	["UK", "Somewhat disagree", 2, 39, DateTime.new(2013,6,30), "I encourage my friends to use the brands I really like."],		
	["total", "Strongly disagree", 1, 610, DateTime.new(2013,6,30), "I encourage my friends to use the brands I really like."],
	["US", "Strongly disagree", 1, 26, DateTime.new(2013,6,30), "I encourage my friends to use the brands I really like."],
	["UK", "Strongly disagree", 1, 41, DateTime.new(2013,6,30), "I encourage my friends to use the brands I really like."],								
	# Question 9
	["total", "Strongly Agree", 5, 1742, DateTime.new(2013,6,30), "I would rather pay more for a well-known brand than take a chance on a brand that isn't as established."],
	["US", "Strongly Agree", 5, 78, DateTime.new(2013,6,30), "I would rather pay more for a well-known brand than take a chance on a brand that isn't as established."],
	["UK", "Strongly Agree", 5, 56, DateTime.new(2013,6,30), "I would rather pay more for a well-known brand than take a chance on a brand that isn't as established."],
	["total", "Somewhat Agree", 4, 3497, DateTime.new(2013,6,30), "I would rather pay more for a well-known brand than take a chance on a brand that isn't as established."],
	["US", "Somewhat Agree", 4, 170, DateTime.new(2013,6,30), "I would rather pay more for a well-known brand than take a chance on a brand that isn't as established."],
	["UK", "Somewhat Agree", 4, 168, DateTime.new(2013,6,30), "I would rather pay more for a well-known brand than take a chance on a brand that isn't as established."],	
	["total", "Neither agree nor disagree", 3, 3328, DateTime.new(2013,6,30), "I would rather pay more for a well-known brand than take a chance on a brand that isn't as established."],
	["US", "Neither agree nor disagree", 3, 162, DateTime.new(2013,6,30), "I would rather pay more for a well-known brand than take a chance on a brand that isn't as established."],
	["UK", "Neither agree nor disagree", 3, 166, DateTime.new(2013,6,30), "I would rather pay more for a well-known brand than take a chance on a brand that isn't as established."],	
	["total", "Somewhat disagree", 2, 1492, DateTime.new(2013,6,30), "I would rather pay more for a well-known brand than take a chance on a brand that isn't as established."],
	["US", "Somewhat disagree", 2, 70, DateTime.new(2013,6,30), "I would rather pay more for a well-known brand than take a chance on a brand that isn't as established."],
	["UK", "Somewhat disagree", 2, 94, DateTime.new(2013,6,30), "I would rather pay more for a well-known brand than take a chance on a brand that isn't as established."],		
	["total", "Strongly disagree", 1, 516, DateTime.new(2013,6,30), "I would rather pay more for a well-known brand than take a chance on a brand that isn't as established."],
	["US", "Strongly disagree", 1, 20, DateTime.new(2013,6,30), "I would rather pay more for a well-known brand than take a chance on a brand that isn't as established."],
	["UK", "Strongly disagree", 1, 19, DateTime.new(2013,6,30), "I would rather pay more for a well-known brand than take a chance on a brand that isn't as established."],				
	# Question 10
	["total", "Strongly Agree", 5, 1617, DateTime.new(2013,6,30), "Following a brand on a social networking site (e.g., Facebook, Twitter) is a waste of time."],
	["US", "Strongly Agree", 5, 87, DateTime.new(2013,6,30), "Following a brand on a social networking site (e.g., Facebook, Twitter) is a waste of time."],
	["UK", "Strongly Agree", 5, 85, DateTime.new(2013,6,30), "Following a brand on a social networking site (e.g., Facebook, Twitter) is a waste of time."],
	["total", "Somewhat Agree", 4, 2403, DateTime.new(2013,6,30), "Following a brand on a social networking site (e.g., Facebook, Twitter) is a waste of time."],
	["US", "Somewhat Agree", 4, 100, DateTime.new(2013,6,30), "Following a brand on a social networking site (e.g., Facebook, Twitter) is a waste of time."],
	["UK", "Somewhat Agree", 4, 121, DateTime.new(2013,6,30), "Following a brand on a social networking site (e.g., Facebook, Twitter) is a waste of time."],	
	["total", "Neither agree nor disagree", 3, 3775, DateTime.new(2013,6,30), "Following a brand on a social networking site (e.g., Facebook, Twitter) is a waste of time."],
	["US", "Neither agree nor disagree", 3, 179, DateTime.new(2013,6,30), "Following a brand on a social networking site (e.g., Facebook, Twitter) is a waste of time."],
	["UK", "Neither agree nor disagree", 3, 201, DateTime.new(2013,6,30), "Following a brand on a social networking site (e.g., Facebook, Twitter) is a waste of time."],	
	["total", "Somewhat disagree", 2, 1924, DateTime.new(2013,6,30), "Following a brand on a social networking site (e.g., Facebook, Twitter) is a waste of time."],
	["US", "Somewhat disagree", 2, 97, DateTime.new(2013,6,30), "Following a brand on a social networking site (e.g., Facebook, Twitter) is a waste of time."],
	["UK", "Somewhat disagree", 2, 69, DateTime.new(2013,6,30), "Following a brand on a social networking site (e.g., Facebook, Twitter) is a waste of time."],		
	["total", "Strongly disagree", 1, 855, DateTime.new(2013,6,30), "Following a brand on a social networking site (e.g., Facebook, Twitter) is a waste of time."],
	["US", "Strongly disagree", 1, 39, DateTime.new(2013,6,30), "Following a brand on a social networking site (e.g., Facebook, Twitter) is a waste of time."],
	["UK", "Strongly disagree", 1, 27, DateTime.new(2013,6,30), "Following a brand on a social networking site (e.g., Facebook, Twitter) is a waste of time."],		
	# Question 11
	["total", "Strongly Agree", 5, 1391, DateTime.new(2013,6,30), "I only follow brands on social media to get discounts/special deals."],
	["US", "Strongly Agree", 5, 65, DateTime.new(2013,6,30), "I only follow brands on social media to get discounts/special deals."],
	["UK", "Strongly Agree", 5, 45, DateTime.new(2013,6,30), "I only follow brands on social media to get discounts/special deals."],
	["total", "Somewhat Agree", 4, 2891, DateTime.new(2013,6,30), "I only follow brands on social media to get discounts/special deals."],
	["US", "Somewhat Agree", 4, 118, DateTime.new(2013,6,30), "I only follow brands on social media to get discounts/special deals."],
	["UK", "Somewhat Agree", 4, 129, DateTime.new(2013,6,30), "I only follow brands on social media to get discounts/special deals."],	
	["total", "Neither agree nor disagree", 3, 3567, DateTime.new(2013,6,30), "I only follow brands on social media to get discounts/special deals."],
	["US", "Neither agree nor disagree", 3, 177, DateTime.new(2013,6,30), "I only follow brands on social media to get discounts/special deals."],
	["UK", "Neither agree nor disagree", 3, 208, DateTime.new(2013,6,30), "I only follow brands on social media to get discounts/special deals."],	
	["total", "Somewhat disagree", 2, 1548, DateTime.new(2013,6,30), "I only follow brands on social media to get discounts/special deals."],
	["US", "Somewhat disagree", 2, 66, DateTime.new(2013,6,30), "I only follow brands on social media to get discounts/special deals."],
	["UK", "Somewhat disagree", 2, 66, DateTime.new(2013,6,30), "I only follow brands on social media to get discounts/special deals."],		
	["total", "Strongly disagree", 1, 1176, DateTime.new(2013,6,30), "I only follow brands on social media to get discounts/special deals."],
	["US", "Strongly disagree", 1, 74, DateTime.new(2013,6,30), "I only follow brands on social media to get discounts/special deals."],
	["UK", "Strongly disagree", 1, 54, DateTime.new(2013,6,30), "I only follow brands on social media to get discounts/special deals."],			
	# Question 12
	["total", "Strongly Agree", 5, 3531, DateTime.new(2013,6,30), "In general, brands don't take young people seriously enough."],
	["US", "Strongly Agree", 5, 155, DateTime.new(2013,6,30), "In general, brands don't take young people seriously enough."],
	["UK", "Strongly Agree", 5, 149, DateTime.new(2013,6,30), "In general, brands don't take young people seriously enough."],
	["total", "Somewhat Agree", 4, 1148, DateTime.new(2013,6,30), "In general, brands don't take young people seriously enough."],
	["US", "Somewhat Agree", 4, 45, DateTime.new(2013,6,30), "In general, brands don't take young people seriously enough."],
	["UK", "Somewhat Agree", 4, 44, DateTime.new(2013,6,30), "In general, brands don't take young people seriously enough."],	
	["total", "Neither agree nor disagree", 3, 4308, DateTime.new(2013,6,30), "In general, brands don't take young people seriously enough."],
	["US", "Neither agree nor disagree", 3, 210, DateTime.new(2013,6,30), "In general, brands don't take young people seriously enough."],
	["UK", "Neither agree nor disagree", 3, 256, DateTime.new(2013,6,30), "In general, brands don't take young people seriously enough."],	
	["total", "Somewhat disagree", 2, 1945, DateTime.new(2013,6,30), "In general, brands don't take young people seriously enough."],
	["US", "Somewhat disagree", 2, 99, DateTime.new(2013,6,30), "In general, brands don't take young people seriously enough."],
	["UK", "Somewhat disagree", 2, 74, DateTime.new(2013,6,30), "In general, brands don't take young people seriously enough."],		
	["total", "Strongly disagree", 1, 790, DateTime.new(2013,6,30), "In general, brands don't take young people seriously enough."],
	["US", "Strongly disagree", 1, 37, DateTime.new(2013,6,30), "In general, brands don't take young people seriously enough."],
	["UK", "Strongly disagree", 1, 23, DateTime.new(2013,6,30), "In general, brands don't take young people seriously enough."],				
	# Question 13
	["total", "Strongly Agree", 5, 2025, DateTime.new(2013,6,30), "Most brands pay too little attention to older consumers."],
	["US", "Strongly Agree", 5, 70, DateTime.new(2013,6,30), "Most brands pay too little attention to older consumers."],
	["UK", "Strongly Agree", 5, 80, DateTime.new(2013,6,30), "Most brands pay too little attention to older consumers."],
	["total", "Somewhat Agree", 4, 3861, DateTime.new(2013,6,30), "Most brands pay too little attention to older consumers."],
	["US", "Somewhat Agree", 4, 193, DateTime.new(2013,6,30), "Most brands pay too little attention to older consumers."],
	["UK", "Somewhat Agree", 4, 193, DateTime.new(2013,6,30), "Most brands pay too little attention to older consumers."],	
	["total", "Neither agree nor disagree", 3, 3558, DateTime.new(2013,6,30), "Most brands pay too little attention to older consumers."],
	["US", "Neither agree nor disagree", 3, 185, DateTime.new(2013,6,30), "Most brands pay too little attention to older consumers."],
	["UK", "Neither agree nor disagree", 3, 198, DateTime.new(2013,6,30), "Most brands pay too little attention to older consumers."],	
	["total", "Somewhat disagree", 2, 907, DateTime.new(2013,6,30), "Most brands pay too little attention to older consumers."],
	["US", "Somewhat disagree", 2, 35, DateTime.new(2013,6,30), "Most brands pay too little attention to older consumers."],
	["UK", "Somewhat disagree", 2, 27, DateTime.new(2013,6,30), "Most brands pay too little attention to older consumers."],		
	["total", "Strongly disagree", 1, 223, DateTime.new(2013,6,30), "Most brands pay too little attention to older consumers."],
	["US", "Strongly disagree", 1, 18, DateTime.new(2013,6,30), "Most brands pay too little attention to older consumers."],
	["UK", "Strongly disagree", 1, 4, DateTime.new(2013,6,30), "Most brands pay too little attention to older consumers."],					
	# Question 14
	["total", "Strongly Agree", 5, 1468, DateTime.new(2013,6,30), "As long as a brand is useful, I don't care if it shares my values."],
	["US", "Strongly Agree", 5, 77, DateTime.new(2013,6,30), "As long as a brand is useful, I don't care if it shares my values."],
	["UK", "Strongly Agree", 5, 52, DateTime.new(2013,6,30), "As long as a brand is useful, I don't care if it shares my values."],
	["total", "Somewhat Agree", 4, 3228, DateTime.new(2013,6,30), "As long as a brand is useful, I don't care if it shares my values."],
	["US", "Somewhat Agree", 4, 116, DateTime.new(2013,6,30), "As long as a brand is useful, I don't care if it shares my values."],
	["UK", "Somewhat Agree", 4, 126, DateTime.new(2013,6,30), "As long as a brand is useful, I don't care if it shares my values."],	
	["total", "Neither agree nor disagree", 3, 3914, DateTime.new(2013,6,30), "As long as a brand is useful, I don't care if it shares my values."],
	["US", "Neither agree nor disagree", 3, 187, DateTime.new(2013,6,30), "As long as a brand is useful, I don't care if it shares my values."],
	["UK", "Neither agree nor disagree", 3, 236, DateTime.new(2013,6,30), "As long as a brand is useful, I don't care if it shares my values."],	
	["total", "Somewhat disagree", 2, 1416, DateTime.new(2013,6,30), "As long as a brand is useful, I don't care if it shares my values."],
	["US", "Somewhat disagree", 2, 86, DateTime.new(2013,6,30), "As long as a brand is useful, I don't care if it shares my values."],
	["UK", "Somewhat disagree", 2, 61, DateTime.new(2013,6,30), "As long as a brand is useful, I don't care if it shares my values."],		
	["total", "Strongly disagree", 1, 547, DateTime.new(2013,6,30), "As long as a brand is useful, I don't care if it shares my values."],
	["US", "Strongly disagree", 1, 34, DateTime.new(2013,6,30), "As long as a brand is useful, I don't care if it shares my values."],
	["UK", "Strongly disagree", 1, 28, DateTime.new(2013,6,30), "As long as a brand is useful, I don't care if it shares my values."],						
	# Question 15
	["total", "Strongly Agree", 5, 2587, DateTime.new(2013,6,30), "When I find a brand that fits my personality, I tend to be loyal to it."],
	["US", "Strongly Agree", 5, 132, DateTime.new(2013,6,30), "When I find a brand that fits my personality, I tend to be loyal to it."],
	["UK", "Strongly Agree", 5, 66, DateTime.new(2013,6,30), "When I find a brand that fits my personality, I tend to be loyal to it."],
	["total", "Somewhat Agree", 4, 4642, DateTime.new(2013,6,30), "When I find a brand that fits my personality, I tend to be loyal to it."],
	["US", "Somewhat Agree", 4, 218, DateTime.new(2013,6,30), "When I find a brand that fits my personality, I tend to be loyal to it."],
	["UK", "Somewhat Agree", 4, 255, DateTime.new(2013,6,30), "When I find a brand that fits my personality, I tend to be loyal to it."],	
	["total", "Neither agree nor disagree", 3, 2563, DateTime.new(2013,6,30), "When I find a brand that fits my personality, I tend to be loyal to it."],
	["US", "Neither agree nor disagree", 3, 133, DateTime.new(2013,6,30), "When I find a brand that fits my personality, I tend to be loyal to it."],
	["UK", "Neither agree nor disagree", 3, 153, DateTime.new(2013,6,30), "When I find a brand that fits my personality, I tend to be loyal to it."],	
	["total", "Somewhat disagree", 2, 544, DateTime.new(2013,6,30), "When I find a brand that fits my personality, I tend to be loyal to it."],
	["US", "Somewhat disagree", 2, 13, DateTime.new(2013,6,30), "When I find a brand that fits my personality, I tend to be loyal to it."],
	["UK", "Somewhat disagree", 2, 21, DateTime.new(2013,6,30), "When I find a brand that fits my personality, I tend to be loyal to it."],		
	["total", "Strongly disagree", 1, 237, DateTime.new(2013,6,30), "When I find a brand that fits my personality, I tend to be loyal to it."],
	["US", "Strongly disagree", 1, 4, DateTime.new(2013,6,30), "When I find a brand that fits my personality, I tend to be loyal to it."],
	["UK", "Strongly disagree", 1, 7, DateTime.new(2013,6,30), "When I find a brand that fits my personality, I tend to be loyal to it."],							

]

Response.delete_all
response_list.each do |country, answer, answer_rank, answer_count, date, question_title|
	@question_title = Question.find_by title: question_title	
	Response.create(country: country, answer: answer, answer_rank: answer_rank, answer_count: answer_count, date: date, question_id: @question_title.id)
end


puts "successfully seeded reports questions and responses"